remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

title: 全民希臘文 (BG4E)
description: Biblical Greek for Everyone (BG4E)
show_downloads: false

# theme: jekyll-theme-leap-day
# markdown: GFM